#! /bin/bash
GRANT="GRANT ALL ON ${MYSQL_DATABASE}.* TO ${MYSQL_USER}@'localhost' IDENTIFIED BY ${MYSQL_PASSWORD} WITH GRANT OPTION; FLUSH PRIVILEGES"
echo $GRANT | mysql -u ${MYSQL_ROOT_USER} -p ${MYSQL_ROOT_PASSWORD}